//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::A8, // Ignition 1
	Gpio::C9, // Ignition 2
	Gpio::A10, // Ignition 3
	Gpio::C8, // Ignition 4
	Gpio::E0, // Injector 1
	Gpio::E6, // Injector 2
	Gpio::D9, // Injector 3
	Gpio::E3, // Injector 4
	Gpio::E4, // Fuel Pump (PE4)
	Gpio::E5, // NOS (PE5)
	Gpio::B8, // Tach (PB8)
	Gpio::B9, // Boost (PB9)
	Gpio::B14, // ETB_DIS/StepDir
	Gpio::B15, // ETB_DIR/StepStep
	Gpio::C5, // PPS2 (PC5)
	Gpio::C6, // ETB PWM
	Gpio::C10, // VVT1 (C10)
	Gpio::C11, // VVT2 (C11)
	Gpio::C13, // Fan (PC13)
	Gpio::D4, // CAM2 (PD4)
	Gpio::D5, // USART-TX (PD5)
	Gpio::D6, // USART-RX (PD6)
	Gpio::D2, // Ignition 7 (PD2)
	Gpio::D3, // Ignition 8 (PD3)
	Gpio::D10, // Injector 5 (PD10)
	Gpio::D11, // Injector 6 (PD11)
	Gpio::D12, // Injector 7 (PD12)
	Gpio::D13, // Injector 8 (PD13)
	Gpio::D14, // Threshold (PD14)
	Gpio::E11, // Ignition 5 (PE11)
	Gpio::E12, // Ignition 5 (PE12)
	Gpio::E14, // Extra I/O PE14
	Gpio::E15, // Idle (PE15)
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Fuel Pump (PE4)",
// "NOS (PE5)",
// "Tach (PB8)",
// "Boost (PB9)",
// "ETB_DIS/StepDir",
// "ETB_DIR/StepStep",
// "PPS2 (PC5)",
// "ETB PWM",
// "VVT1 (C10)",
// "VVT2 (C11)",
// "Fan (PC13)",
// "CAM2 (PD4)",
// "USART-TX (PD5)",
// "USART-RX (PD6)",
// "Ignition 7 (PD2)",
// "Ignition 8 (PD3)",
// "Injector 5 (PD10)",
// "Injector 6 (PD11)",
// "Injector 7 (PD12)",
// "Injector 8 (PD13)",
// "Threshold (PD14)",
// "Ignition 5 (PE11)",
// "Ignition 5 (PE12)",
// "Extra I/O PE14",
// "Idle (PE15)",
}
