//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A10: return "Ignition 3";
		case Gpio::A6: return "CMP";
		case Gpio::A7: return "FlexFuel";
		case Gpio::A8: return "Ignition 1";
		case Gpio::B1: return "CKP";
		case Gpio::B14: return "ETB_DIS/StepDir";
		case Gpio::B15: return "ETB_DIR/StepStep";
		case Gpio::B8: return "Tach (PB8)";
		case Gpio::B9: return "Boost (PB9)";
		case Gpio::C10: return "VVT1 (C10)";
		case Gpio::C11: return "VVT2 (C11)";
		case Gpio::C13: return "Fan (PC13)";
		case Gpio::C5: return "PPS2 (PC5)";
		case Gpio::C6: return "ETB PWM";
		case Gpio::C8: return "Ignition 4";
		case Gpio::C9: return "Ignition 2";
		case Gpio::D10: return "Injector 5 (PD10)";
		case Gpio::D11: return "Injector 6 (PD11)";
		case Gpio::D12: return "Injector 7 (PD12)";
		case Gpio::D13: return "Injector 8 (PD13)";
		case Gpio::D14: return "Threshold (PD14)";
		case Gpio::D2: return "Ignition 7 (PD2)";
		case Gpio::D3: return "Ignition 8 (PD3)";
		case Gpio::D4: return "CAM2 (PD4)";
		case Gpio::D5: return "USART-TX (PD5)";
		case Gpio::D6: return "USART-RX (PD6)";
		case Gpio::D9: return "Injector 3";
		case Gpio::E0: return "Injector 1";
		case Gpio::E11: return "Ignition 5 (PE11)";
		case Gpio::E12: return "Ignition 6 (PE12)";
		case Gpio::E14: return "Extra I/O PE14";
		case Gpio::E15: return "Idle (PE15)";
		case Gpio::E2: return "Clutch";
		case Gpio::E3: return "Injector 4";
		case Gpio::E4: return "Fuel Pump (PE4)";
		case Gpio::E5: return "NOS (PE5)";
		case Gpio::E6: return "Injector 2";
		default: return nullptr;
	}
	return nullptr;
}
